### ISSUE TITLE
Extension doesn't support syntax used by Azure Devops Wiki Markdown

### ISSUE THREAD

**Issue by wibblemonkey** [wibblemonkey/vscode-markdown-auto-toc#2]
The [markdown syntax supported by the Wiki feature of Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=vsts#table-of-contents-toc-for-wiki-pages) uses `[[_TOC_]]` to generate the table of contacts, so the extension should support this as well.

**Comment by Camo30** [comment]
Should work by adding the following line:
`options["markerPattern"] = /^\[\[_?toc_?\]\]/im;`

...only tested with Azure DevOps Wiki. Would be great to get that soon.

**Comment by wibblemonkey** [comment]
Cheers!
I'm working on another extension to provide an Azure DevOps Wiki style markdown preview in VS Code and was holding off on implementing these changes until it was ready to go, but now I know that someone is waiting for the change I'll try to get a minor update out this weekend. 🙂

**Comment by wibblemonkey** [comment]
Fixed in 0.3.0
